name: "Android Resource Translator"
description: "Checks Android resource files for missing translations and auto-translates using OpenAI."
author: "Duarte Barbosa"

branding:
  icon: 'book-open'
  color: 'green'

env:
  OPENAI_API_KEY:
    description: "OpenAI API key for translation (passed via secrets)."

inputs:
  resources_paths:
    description: "Comma-separated paths to the Android resource directories (e.g., './app/src/main/res, ./library/src/main/res')."
    required: false
    default: "${{ github.workspace }}"
  auto_translate:
    description: "Automatically translate missing resources. Set to 'true' to enable."
    required: false
    default: "true"
  log_trace:
    description: "Enable detailed logging. Set to 'true' to enable."
    required: false
    default: "false"
  openai_model:
    description: "Specify the OpenAI model to use for translation."
    required: false
    default: "gpt-3.5-turbo"
  project_context:
    description: "Additional project context to include in translation prompts."
    required: false
    default: ""
  ignore_folders:
    description: "Comma-separated list of folder names to ignore during resource scanning (e.g., build)."
    required: false
    default: "build"

outputs:
  translation_report:
    description: "A translation report in markdown format"
    
runs:
  using: 'docker'
  image: 'Dockerfile'
