name: build

on:
  push:
    branches: [ main ]
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v5

    - name: Setup Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.10'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Run Python unit tests
      run: |
        python3 -u -m unittest app/tests/test_report.py
        python3 -u -m unittest app/tests/test_resource_parser.py
        python3 -u -m unittest app/tests/test_translation.py
        python3 -u -m unittest app/tests/test_xml_formatting.py
        python3 -u -m unittest app/tests/test_gitignore.py
        python3 -u -m unittest app/tests/test_integration.py
        python3 -u -m unittest app/tests/test_language_utils.py

    - name: Verify that the Docker image for the action builds
      run: docker build . --file Dockerfile
